import PropTypes from "prop-types";
import { useState } from "react";
import { IoCloseOutline } from "react-icons/io5";

const PRODUCT_TYPES = ["aliment", "épice", "plante"];

const EMPTY_PRODUCT = {
  name: "",
  type: "aliment",
  description: "",
  symptoms: [],
  badForSymptoms: [],
  properties: [],
  uses: [],
  contraindications: [],
  tips: [],
  image: "",
  pregnancySafe: {
    safe: true,
    trimester: [],
    details: "",
    precautions: "",
    source: "",
  },
  childrenAge: null,
  allergens: [],
  alternatives: [],
  verifiedByProfessional: false,
  autoGenerated: false,
  sources: { scientific: [], traditional: [] },
  imageCredit: { author: "", source: "", url: "" },
};

export default function AdminProductForm({ product, onSave, onCancel }) {
  const isEditing = !!product;
  const [form, setForm] = useState(() =>
    isEditing ? { ...EMPTY_PRODUCT, ...product } : { ...EMPTY_PRODUCT },
  );

  const handleChange = (field, value) => {
    setForm((prev) => ({ ...prev, [field]: value }));
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    onSave({
      ...form,
      childrenAge:
        form.childrenAge === "" ? null : Number(form.childrenAge) || null,
    });
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
      <div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-xl border-2 border-dashed border-neutral-300 bg-white p-6 shadow-xl dark:border-neutral-600 dark:bg-neutral-800">
        <div className="mb-6 flex items-center justify-between">
          <h2 className="text-lg font-bold text-neutral-800 dark:text-white">
            {isEditing ? "Modifier le produit" : "Ajouter un produit"}
          </h2>
          <button
            onClick={onCancel}
            className="cursor-pointer rounded-lg p-1 text-neutral-500 transition-colors hover:bg-neutral-100 hover:text-red-500 dark:hover:bg-neutral-700"
            aria-label="Fermer"
          >
            <IoCloseOutline className="text-xl" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4">
          {/* Nom */}
          <div>
            <label
              htmlFor="product-name"
              className="mb-1 block text-sm font-medium text-neutral-700 dark:text-neutral-300"
            >
              Nom *
            </label>
            <input
              id="product-name"
              type="text"
              value={form.name}
              onChange={(e) => handleChange("name", e.target.value)}
              required
              className="w-full rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm text-neutral-800 outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/20 dark:border-neutral-600 dark:bg-neutral-700 dark:text-white"
            />
          </div>

          {/* Type */}
          <div>
            <label
              htmlFor="product-type"
              className="mb-1 block text-sm font-medium text-neutral-700 dark:text-neutral-300"
            >
              Type *
            </label>
            <select
              id="product-type"
              value={form.type}
              onChange={(e) => handleChange("type", e.target.value)}
              className="w-full rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm text-neutral-800 outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/20 dark:border-neutral-600 dark:bg-neutral-700 dark:text-white"
            >
              {PRODUCT_TYPES.map((type) => (
                <option key={type} value={type}>
                  {type.charAt(0).toUpperCase() + type.slice(1)}
                </option>
              ))}
            </select>
          </div>

          {/* Description */}
          <div>
            <label
              htmlFor="product-description"
              className="mb-1 block text-sm font-medium text-neutral-700 dark:text-neutral-300"
            >
              Description *
            </label>
            <textarea
              id="product-description"
              value={form.description}
              onChange={(e) => handleChange("description", e.target.value)}
              required
              rows={4}
              className="w-full rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm text-neutral-800 outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/20 dark:border-neutral-600 dark:bg-neutral-700 dark:text-white"
            />
          </div>

          {/* Image URL */}
          <div>
            <label
              htmlFor="product-image"
              className="mb-1 block text-sm font-medium text-neutral-700 dark:text-neutral-300"
            >
              URL Image
            </label>
            <input
              id="product-image"
              type="url"
              value={form.image}
              onChange={(e) => handleChange("image", e.target.value)}
              className="w-full rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm text-neutral-800 outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/20 dark:border-neutral-600 dark:bg-neutral-700 dark:text-white"
            />
          </div>

          <div className="grid grid-cols-2 gap-4">
            {/* Vérifié par un professionnel */}
            <div className="flex items-center gap-2">
              <input
                id="product-verified"
                type="checkbox"
                checked={form.verifiedByProfessional}
                onChange={(e) =>
                  handleChange("verifiedByProfessional", e.target.checked)
                }
                className="h-4 w-4 rounded accent-emerald-600"
              />
              <label
                htmlFor="product-verified"
                className="text-sm text-neutral-700 dark:text-neutral-300"
              >
                Vérifié par un professionnel
              </label>
            </div>

            {/* Âge enfants */}
            <div>
              <label
                htmlFor="product-children-age"
                className="mb-1 block text-sm font-medium text-neutral-700 dark:text-neutral-300"
              >
                Âge min. enfants
              </label>
              <input
                id="product-children-age"
                type="number"
                min="0"
                max="18"
                value={form.childrenAge ?? ""}
                onChange={(e) => handleChange("childrenAge", e.target.value)}
                placeholder="Vide = tous âges"
                className="w-full rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm text-neutral-800 outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/20 dark:border-neutral-600 dark:bg-neutral-700 dark:text-white"
              />
            </div>
          </div>

          {/* Grossesse */}
          <div>
            <label
              htmlFor="product-pregnancy"
              className="mb-1 block text-sm font-medium text-neutral-700 dark:text-neutral-300"
            >
              Grossesse
            </label>
            <select
              id="product-pregnancy"
              value={
                form.pregnancySafe?.safe === true
                  ? "ok"
                  : form.pregnancySafe?.safe === false
                    ? "interdit"
                    : "variant"
              }
              onChange={(e) => {
                const val = e.target.value;
                handleChange("pregnancySafe", {
                  ...form.pregnancySafe,
                  safe: val === "ok" ? true : val === "interdit" ? false : null,
                });
              }}
              className="w-full rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm text-neutral-800 outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/20 dark:border-neutral-600 dark:bg-neutral-700 dark:text-white"
            >
              <option value="ok">Autorisé</option>
              <option value="variant">Avec précautions</option>
              <option value="interdit">Interdit</option>
            </select>
          </div>

          {/* Allergènes */}
          <div>
            <label
              htmlFor="product-allergens"
              className="mb-1 block text-sm font-medium text-neutral-700 dark:text-neutral-300"
            >
              Allergènes (séparés par des virgules)
            </label>
            <input
              id="product-allergens"
              type="text"
              value={form.allergens.join(", ")}
              onChange={(e) =>
                handleChange(
                  "allergens",
                  e.target.value
                    .split(",")
                    .map((a) => a.trim())
                    .filter(Boolean),
                )
              }
              placeholder="ex: agrumes, citron"
              className="w-full rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm text-neutral-800 outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/20 dark:border-neutral-600 dark:bg-neutral-700 dark:text-white"
            />
          </div>

          {/* Actions */}
          <div className="flex gap-3 pt-4">
            <button
              type="submit"
              className="flex-1 cursor-pointer rounded-lg bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white transition-colors hover:bg-emerald-700 dark:bg-emerald-700 dark:hover:bg-emerald-600"
            >
              {isEditing ? "Enregistrer" : "Ajouter"}
            </button>
            <button
              type="button"
              onClick={onCancel}
              className="cursor-pointer rounded-lg border border-neutral-300 px-4 py-2.5 text-sm font-medium text-neutral-600 transition-colors hover:bg-neutral-100 dark:border-neutral-600 dark:text-neutral-400 dark:hover:bg-neutral-700"
            >
              Annuler
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

AdminProductForm.propTypes = {
  product: PropTypes.object,
  onSave: PropTypes.func.isRequired,
  onCancel: PropTypes.func.isRequired,
};
